import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import { Poppins } from 'next/font/google';
import Footer from "@/components/Footer/Footer";
import ImportJs from "@/components/ImportJs";
import "bootstrap/dist/css/bootstrap.min.css";

const poppins = Poppins({
    subsets: ['latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], 
    display: 'swap',
    variable: '--font-poppins', 
})

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${poppins.variable} font-poppins`}>
                <Navbar />
                <ImportJs />
                {children}
                <Footer />
            </body>
        </html>
    );
}
